import example_1, fill_form, find_by_text_link, checkbox_radio, select, script_execute, file_upload, alerts
import windows, waiters, test_text
import reg_form_for_review
# example_1.example()
# fill_form.fill_form()
# find_by_text_link.find()
# fill_form.fill_form_in_circle()
# fill_form.fill_form_xpath()
# fill_form.fill_form_registration_1()
# fill_form.fill_form_registration_2()
# reg_form_for_review.fill_form_registration()
# reg_form_for_review.fill_form_registration_2()
# checkbox_radio.checkbox_radio_1()
# checkbox_radio.checkbox_radio_2()
# select.select_1()
# script_execute.script_1()
# script_execute.script_2()
# script_execute.script_3()
# file_upload.file_upload_1()
# alerts.alert_1()
# windows.new_window()
# waiters.wait_1()
# waiters.wait_2()
# waiters.wait_3()
# test_text.test_input_text(11, 11)
test_text.test_substring("some_text","some")
